CREATE TABLE ataques (idAtaque INTEGER AUTO_INCREMENT NOT NULL, categoriaAtaque VARCHAR(20), efecto VARCHAR(255), nombreAtaque VARCHAR(50), potencia INTEGER, PP INTEGER, tipoDeAtaque VARCHAR(20), PRIMARY KEY (idAtaque))
CREATE TABLE entrenador (idEntrenador INTEGER AUTO_INCREMENT NOT NULL, nomEntrenador VARCHAR(30) NOT NULL, PRIMARY KEY (idEntrenador))
CREATE TABLE habilidad (idHabilidad INTEGER AUTO_INCREMENT NOT NULL, descripcionHabilidad VARCHAR(200), nombreHabilidad VARCHAR(50) NOT NULL, PRIMARY KEY (idHabilidad))
CREATE TABLE pokemon (idPokemon INTEGER AUTO_INCREMENT NOT NULL, alias VARCHAR(30), nivel INTEGER NOT NULL, nombre_pokemon VARCHAR(30) NOT NULL, numero_pokedex INTEGER NOT NULL, segundo_tipo VARCHAR(255), tipoPokemon VARCHAR(255), idEntrenador INTEGER, idHabilidad INTEGER, PRIMARY KEY (idPokemon))
CREATE TABLE `pokemon_ataque` (metodoAprendizaje VARCHAR(50), id_ataque INTEGER NOT NULL, id_pokemon INTEGER NOT NULL, PRIMARY KEY (id_ataque, id_pokemon))
CREATE TABLE pokemon_ataques (Pokemon_idPokemon INTEGER NOT NULL, listaAtaques_idAtaque INTEGER NOT NULL, PRIMARY KEY (Pokemon_idPokemon, listaAtaques_idAtaque))
ALTER TABLE pokemon ADD CONSTRAINT FK_pokemon_idHabilidad FOREIGN KEY (idHabilidad) REFERENCES habilidad (idHabilidad)
ALTER TABLE pokemon ADD CONSTRAINT FK_pokemon_idEntrenador FOREIGN KEY (idEntrenador) REFERENCES entrenador (idEntrenador)
ALTER TABLE `pokemon_ataque` ADD CONSTRAINT `FK_pokemon_ataque_id_ataque` FOREIGN KEY (id_ataque) REFERENCES ataques (idAtaque)
ALTER TABLE `pokemon_ataque` ADD CONSTRAINT `FK_pokemon_ataque_id_pokemon` FOREIGN KEY (id_pokemon) REFERENCES pokemon (idPokemon)
ALTER TABLE pokemon_ataques ADD CONSTRAINT FK_pokemon_ataques_Pokemon_idPokemon FOREIGN KEY (Pokemon_idPokemon) REFERENCES pokemon (idPokemon)
ALTER TABLE pokemon_ataques ADD CONSTRAINT FK_pokemon_ataques_listaAtaques_idAtaque FOREIGN KEY (listaAtaques_idAtaque) REFERENCES ataques (idAtaque)
