/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Views.AñadirEntrenador;
import controladores.JPanelimagen;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author yoriel
 */
public class MenuEntrenadores extends javax.swing.JFrame {

    /**
     * Creates new form PantallaInicio
     */
    public MenuEntrenadores() {
        initComponents();
        imagenFondoEntrenador();
        setLocationRelativeTo(null);
        this.setResizable(false);
        
        //Para que la lista sea transparente o bueno, tengo el color del fondo
        ListaEntrenadores.setOpaque(false);             // Quita el fondo opaco
        ListaEntrenadores.setBackground(new Color(13,173,239,255)); // Fondo completamente transparente
        ListaEntrenadores.setBorder(BorderFactory.createLineBorder(Color.red));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MenuEntre = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaEntrenadores = new javax.swing.JList<>();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Añadir Entrenador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar Entrenador");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Acceder Pokedex");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Editar Entrenador");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        ListaEntrenadores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaEntrenadores);

        javax.swing.GroupLayout MenuEntreLayout = new javax.swing.GroupLayout(MenuEntre);
        MenuEntre.setLayout(MenuEntreLayout);
        MenuEntreLayout.setHorizontalGroup(
            MenuEntreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuEntreLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(MenuEntreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(56, 56, 56))
        );
        MenuEntreLayout.setVerticalGroup(
            MenuEntreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuEntreLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(178, 178, 178)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuEntreLayout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuEntre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuEntre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      //Obtener el entrenador seleccionado 
   AñadirEntrenador dialog = new AñadirEntrenador(this, true); // 'this' es el JFrame padre
dialog.setVisible(true);
       // Luego de cerrar el diálogo, recarga tus datos para actualizar la vista
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 // Obtener el entrenador seleccionado en la lista
    String entrenadorSeleccionado = ListaEntrenadores.getSelectedValue();
    if (entrenadorSeleccionado == null) {
        // Mostrar mensaje si no hay selección
        javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un entrenador para editar.");
        return;
    }

      // Crear el diálogo pasando el nombre seleccionado
    EditarEntrenador dialog = new EditarEntrenador(this, true, entrenadorSeleccionado);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        // Primero obtenemos el entrenador seleccionado en la lista
    String entrenadorSeleccionado = ListaEntrenadores.getSelectedValue();
    
    if (entrenadorSeleccionado == null) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un entrenador para eliminar.");
        return;
    }
    
    // Pedimos confirmación
    int confirmacion = JOptionPane.showConfirmDialog(
        this, 
        "¿Estás seguro que quieres eliminar al entrenador " + entrenadorSeleccionado + "?",
        "Confirmar eliminación",
        JOptionPane.YES_NO_OPTION
    );
    
    if (confirmacion == JOptionPane.YES_OPTION) {
        // Aquí va la lógica para eliminar el entrenador de la base de datos o lista
        // Por ahora, solo mostramos un mensaje:
        JOptionPane.showMessageDialog(this, "Entrenador " + entrenadorSeleccionado + " eliminado.");
        
        // TODO: eliminar entrenador de la base de datos o estructura de datos
        
        // Además, actualizar la lista para reflejar el cambio
        // Por ejemplo, si usas DefaultListModel:
        // DefaultListModel<String> model = (DefaultListModel<String>) ListaEntrenadores.getModel();
        // model.removeElement(entrenadorSeleccionado);
    }  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     String entrenadorSeleccionado = ListaEntrenadores.getSelectedValue();
    if (entrenadorSeleccionado == null) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un entrenador para acceder a la Pokedex.");
        return;
    }
    
    // Crear la ventana de Pokedex, pasando el entrenador seleccionado
    Pokedex ventanaPokedex = new Pokedex(this, true, entrenadorSeleccionado);
    ventanaPokedex.setLocationRelativeTo(this);
    ventanaPokedex.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

      private void imagenFondoEntrenador(){
           JPanelimagen imagenFondo = new JPanelimagen(MenuEntre, "/Fotos/InterfazEntrenadores.png");
    MenuEntre.add(imagenFondo).repaint();
    
    //estos 3, es para que se quite cualquier fondo o borde del label que use
    //la ventaja del label, es que funciona como fondo, puedo poner botones encima
    MenuEntre.setOpaque(false);
    MenuEntre.setBorder(null);
    MenuEntre.setBackground(new Color (0,0,0));
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEntrenadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEntrenadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEntrenadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEntrenadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEntrenadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaEntrenadores;
    private javax.swing.JPanel MenuEntre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
