/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views;

import Entidades.Ataque;
import Entidades.PokemonAtaque;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yoriel
 */
public class MostrarAtaques extends javax.swing.JDialog {

    /**
     * Creates new form MostrarAtaques
     *
     * @param parent
     * @param modalityType
     */
    private EntityManagerFactory emf;
    public MostrarAtaques(java.awt.Window parent, java.awt.Dialog.ModalityType modalityType) {
        super(parent, modalityType);
        initComponents();
        setTitle("Ataques del Pokémon");
        setLocationRelativeTo(parent);
        setResizable(false);
        
        
        // Inicializar EntityManagerFactory para conexión con BD
        emf = Persistence.createEntityManagerFactory("pokemondb");
    }

    /**
     * Carga los ataques en la tabla.
     *
     * @param ataques Lista de PokemonAtaque para mostrar
     */
   

   public void cargarAtaques(List<PokemonAtaque> ataques) {
   DefaultTableModel modelo = (DefaultTableModel) tablaAtaques.getModel();
modelo.setRowCount(0); // Limpiar la tabla

for (PokemonAtaque pa : ataques) {
    Ataque ataque = pa.getAtaque();

    Object[] fila = new Object[]{
        ataque.getNombreAtaque() != null ? ataque.getNombreAtaque() : "--",
        ataque.getTipo() != null ? ataque.getTipo() : "--",
        ataque.getCategoria() != null ? ataque.getCategoria() : "--",
        ataque.getEfecto() != null ? ataque.getEfecto() : "--",
        ataque.getPotencia() != null ? ataque.getPotencia() : "--",
        ataque.getPp() != null ? ataque.getPp() : "--"
    };

    modelo.addRow(fila);
}

tablaAtaques.repaint();
tablaAtaques.revalidate();
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAtaques = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setBackground(new java.awt.Color(153, 255, 153));

        tablaAtaques.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Tipo", "Categoria", "Efecto", "Potencia", "PP"
            }
        ));
        jScrollPane1.setViewportView(tablaAtaques);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAtaques;
    // End of variables declaration//GEN-END:variables
}
