/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views;

import controladores.JPanelimagen;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author yoriel
 */
public class Pokedex extends javax.swing.JDialog {
    private String entrenador;

    /**
     * Creates new form poki
     */
   public Pokedex(java.awt.Frame parent, boolean modal, String entrenador) {
        super(parent, modal);
        this.entrenador = entrenador;
        initComponents();              // Inicializa los componentes del diseño
        imagenBasePokedex();           // Añade imagen de fondo
        setTitle("Pokedex de " + entrenador); // Título de la ventana
        setLocationRelativeTo(parent); // Centrar respecto al padre
        this.setResizable(false);
        InterfazPokedex.add(new JLabel("Mostrando pokedex de: " + entrenador)); // Ejemplo de contenido
    }

    private void imagenBasePokedex() {
        JPanelimagen imagenFondo = new JPanelimagen(InterfazPokedex, "/Fotos/PokedexAModificar.png");
        InterfazPokedex.add(imagenFondo).repaint();
        InterfazPokedex.setOpaque(false);
        InterfazPokedex.setBorder(null);
        InterfazPokedex.setBackground(new Color(0, 0, 0));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InterfazPokedex = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout InterfazPokedexLayout = new javax.swing.GroupLayout(InterfazPokedex);
        InterfazPokedex.setLayout(InterfazPokedexLayout);
        InterfazPokedexLayout.setHorizontalGroup(
            InterfazPokedexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1103, Short.MAX_VALUE)
        );
        InterfazPokedexLayout.setVerticalGroup(
            InterfazPokedexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InterfazPokedex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(InterfazPokedex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  public static void main(String[] args) {
    // Aseguramos que todo se ejecute en el hilo de eventos de Swing
    javax.swing.SwingUtilities.invokeLater(new Runnable() {
        public void run() {
            // Crear un JFrame falso como "padre" para el JDialog
            javax.swing.JFrame dummyParent = new javax.swing.JFrame();
            dummyParent.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
            dummyParent.setVisible(false); // no mostrarlo

            // Crear y mostrar la Pokedex para pruebas
           Pokedex dialog = new Pokedex(dummyParent, true, "Ash Ketchum");
            dialog.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InterfazPokedex;
    // End of variables declaration//GEN-END:variables
}
